application: sqwiggle-mail
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /_ah/mail/notify@sqwiggle-mail.appspotmail.com
  script: mailer.py

- url: .*
  script: main.py
  
inbound_services:
- mail
